### ISSUE TITLE
Creating specific folders for the outputs

### ISSUE THREAD

**Issue by Oliph** [softwaresaved/ga_group_stats#3]
Currently the summary and the different csv files are created directly on the root folder [report](https://github.com/softwaresaved/ga_group_stats/tree/master/reports). It maybe clearer to have a folder created for each run of the script and a putting the summary on the parent level for clarity. 
Example with the test_set used in the doc:

[report]
|---> [test_set -- 2015-06--2017-02 ]
|------------> [monthly files]
|-----------------------------> ./ga-report- 2016-01.csv
|-----------------------------> ./ga-report- 2016-02.csv
|----------------------------->./ga-report- 2016-02.csv
|-----------------------------> ./...
|------------> ga-summary-2015-06--2017-02.csv
|------------> ga-complete_set-2015-06--2017-02.csv

**Comment by steve-crouch** [comment]
Fixed as above, with some changes: 'monthly files' subdirectory is instead 'monthly_reports', analysis date ranges are also appended to each monthly report CSV filename, and each report filename also includes the URL_LIST_FILE filename. The last two are to avoid ambiguity when sharing results from different analyses.
